config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  scope module: :public do
    resource :customers, only: [:show, :edit, :update]
    resources :items, only: [:index]
    resources :cart_items, only: [:index]
    get '/about' => 'homes#about'
  end

  namespace :admin do
    root to:'homes#top'
    resources :items
    resources :customers, only: [:index]
    resources :genres, only: [:index]
  end
  end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @items = Item.page(params[:page]).per(10)
  end
  
  def show
    @item = Item.find(params[:id])
  end
  
  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:notice] = "商品詳細の変更が完了しました。"
      redirect_to admin_item_path(@item)
    else
      flash[:alert] = "商品詳細の変更内容に不備があります。"
      render :edit
    end
  end
  
  def new
    @item = Item.new
    @genres = Genre.all
  end
  
  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:notice] = "商品の新規登録が完了しました。"
      redirect_to admin_item_path(@item)
    else
      flash[:alert] = "商品の新規登録内容に不備があります。"
      render :new
    end
  end

  private
  
  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active)
  end

end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<% provide(:title, "商品編集") %>
<div class="container">
  <h2 class="text-center my-5">商品編集</h2>
  <div class="row">
    <div class="col-8 offset-2 mb-5">
      <%= form_with model: @item, url: admin_item_path, local: true do |f| %>
      <table>
        <tr>
          <div class="form-group">
            <%= f.label :商品画像, class:"form_label"%>
            <%= f.attachment_field :image,class:"mb-3 ml-3"%>
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <%= f.label :商品名, class:"form_label" %>
            <%= f.text_field :name, placeholder:"商品名",class:"form-control mb-3" %>
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <%= f.label :商品説明, class:"form_label" %>
            <%= f.text_area :introduction, size: "50x5", placeholder:"ここに説明文を記述します",class:"form-control form-control-lg mb-3" %>
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <%= f.label :ジャンル, class:"form_label" %>
            <%= f.collection_select :genre_id, Genre.all, :id, :name, :prompt => "--選択してください--",class:"form-select" %>
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <%= f.label :税抜価格,class:"form_label" %>
            <%= f.text_field :price,size:"15"%>円
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <%= f.label :販売ステータス,class:"form_label my-3" %>
            <%= f.radio_button :is_active, true, checked: true %>
            <%= f.label :is_active, "販売中",class:"form_label" %>
            <%= f.radio_button :is_active, false %>
            <%= f.label :is_active, "販売停止中",class:"form_label" %>
          </div>
        </tr>
        <tr>
          <div class="form-action d-flex justify-content-around">
            <%= f.submit "変更を保存", class:"btn btn-success" %>
            <%= link_to "商品詳細へ戻る",admin_item_path, class:"btn btn-outline-secondary" %>
          </div>
        </tr>
      <% end %>
      </table>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<% provide(:title, "商品") %>
<div class="container">
  <div class="row">
    <div class="col-sm-8 px-sm-0 offset-sm-1">
      <h2 class="my-5">商品一覧</h2>
    </div>
    <div class="col-sm-2 px-sm-0 text-right mt-5">
      <%= link_to new_admin_item_path,class:"btn btn btn-outline-secondary" do %>
        <i class="fas fa-plus fa-2x "></i>
      <% end %>
    </div>
  </div>
  <div class="row"> 
    <div class="col-sm-10 offset-1">
      <%= render 'index', items: @items%>
      <%= paginate @items %>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <h1>商品新規登録</h1>
  <%= form_with model: @item, url: admin_items_path, method: :post do |f| %>
    <div class="row my-3">
      <%= f.label :image, "商品画像", class: "col-lg-1 offset-lg-4" %>
      <%= f.file_field :image, accept: "image/*", class: "col-lg-3"%>
    </div>
    <div class="row mb-3">
      <%= f.label :name, "商品名", class: "col-lg-1 offset-lg-4" %>
      <%= f.text_field :name, class: "col-lg-3" %>
    </div>
    <div class="row mt-3">
      <%= f.label :name, "商品説明", class: "col-lg-1 offset-lg-4" %>
      <%= f.text_area :introduction, class: "col-lg-3" %>
    </div>
    <div class="row my-3">
      <%= f.label :genre_id, "ジャンル", class: "col-lg-1 offset-lg-4" %>
      <div class="col-lg-3">
        <%= f.select :genre_id, @genres.map{ |genre| [genre.name, genre.id] }, { include_blank: '選択してください'}, { required: true } %>
      </div>
    </div>
    <div class="row">
      <%= f.label :price, "税抜価格", class: "col-lg-1 offset-lg-4" %>
      <%= f.text_field :price, class: "col-lg-3" %>
    </div>
    <%= f.submit '新規登録', class: "d-block mx-auto m-3 px-2" %>
  <% end %>
</div>

app/views/admin/items/show.html.erb
<% provide(:title, "商品詳細") %>
<div class="container">
  <h2 class="mt-5 text-center">商品詳細</h2>
  <div class="row align-items-center m-5">
    <div class="col-lg text-center mb-5">
      <%= attachment_image_tag @item, :image, :size => '300x250'%>
    </div>
    <div class="col-lg">
      <table class="table">
        <tr>
          <th>商品名</th>
          <td><%= @item.name %></td>
        </tr>
        <tr>
          <th>商品説明</th>
          <td><%= @item.introduction %></td>
        </tr>
        <tr>
          <th>ジャンル</th>
          <td><%= @item.genre.name %></td>
        </tr>
        <tr>
          <th>
            税込価格<br>
            (税抜き価格)
          </th>
          <td><%= @item.tax_in_price %> (<%= @item.price %>) 円</td>
        </tr>
        <tr>
          <th>販売ステータス</th>
          <td>
            <% if @item.is_active == true %>
            <p class="text-success ">販売中</p>
            <% else %>
            <p class="text-secondary ">販売停止中</p>
            <% end %>
          </td>
        </tr>
        </table>
          <div class="d-flex justify-content-around">
            <p><%= link_to '編集する', edit_admin_item_path(@item.id), class: 'btn btn-success' %></p>
            <p><%= link_to "商品一覧へ戻る", admin_items_path, class:"btn btn-outline-secondary"%></p>
          </div>
        </table>  
   　  </div>
  　</div>
 </div>
 