config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  scope module: :public do
    resource :customers, only: [:show, :edit, :update]
    resources :items, only: [:index]
    resources :cart_items, only: [:index]
    get '/about' => 'homes#about'
  end

  namespace :admin do
    root to:'homes#top'
    resources :items
    resources :customers, only: [:index]
    resources :genres, only: [:index]
  end
  end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @customers = Customer.all.page(params[:page]).per(10)
  end
  
  def show
    @customer = Customer.find(params[:id])
  end
  
  def edit
    @customer = Customer.find(params[:id])
  end
  
  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      flash[:notice] = "会員情報を更新しました。"
      redirect_to admin_customer_path
    else
      render 'edit'
    end
  end
  
  private
  
  def customer_params
    params.require(:customer).permit(:first_name,:last_name,:kana_first_name,:kana_last_name,:postal_code,:address,:phone_number,:email,:is_deleted)
  end
    
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<% provide(:title, "会員情報編集") %>
<div class="container">
  <h2 class="text-center m-5"><%= full_name(@customer)%>さんの会員情報編集</h2>
  <div class="row d-flex justify-content-center">
    
  <%= form_with model: @customer, url: admin_customer_path, local: true do |f| %>
    <div class="col-xs-10 offset-1">
      <div class="form-group col-xs-9">
        <%= f.label :"会員ID", class: "col-sm-4" %>
        <%= f.label :"#{@customer.id}" %>
      </div>
      <div class="form-group col-xs-9">
        <%= f.label :"氏名", class: "col-sm-4 control-label" %>
        <%= f.text_field :last_name, class: "col-sm-3 form-control-static" %>　
        <%= f.text_field :first_name, class: "col-sm-3 form-control-static name" %>
      </div>

      <div class="form-group col-xs-9">
        <%= f.label :"フリガナ", class: "col-sm-4 control-label" %>
        <%= f.text_field :kana_last_name, class: "col-sm-3 form-control-static name" %>
        <%= f.text_field :kana_first_name, class: "col-sm-3 form-control-static name" %>
      </div>
      
      <div class="form-group col-xs-9">
        <%= f.label :"郵便番号", class: "col-sm-4 control-label" %>
        <%= f.text_field :postal_code, class: "col-sm-3" %>
      </div>
      
      <div class="form-group col-xs-9">
        <%= f.label :"住所", class: "col-sm-4 control-label" %>
        <%= f.text_field :address, class: "col-sm-7" %>
      </div>
      
      <div class="form-group col-xs-9">
        <%= f.label :"電話番号", class: "col-sm-4 control-label" %>
        <%= f.text_field :phone_number, class: "col-sm-4" %>
      </div>
      
      <div class="form-group col-xs-9">
        <%= f.label :"メールアドレス", class: "col-sm-4 control-label" %>
        <%= f.text_field :email, class: "col-sm-6" %>
      </div>

      <div class="form-group col-xs-9">
        <%= f.label :"会員ステータス", class: "col-sm-4 control-label" %>
        　<%= f.radio_button :is_deleted, false %>
        　<%= f.label :is_deleted, "有効"%>
        　<%= f.radio_button :is_deleted, true %>
        　<%= f.label :is_deleted, "退会" %>
      </div>
    </div>
      <div class="form-group col-xs-9 d-flex justify-content-around">
        <%= f.submit '変更を保存する' ,class: "btn btn-success" %>
        <%= link_to '会員詳細画面へ戻る',admin_customer_path, class:"btn btn-outline-secondary"%>
      </div>

  <% end %>
    
  </div>
</div>

app/views/admin/customers/index.html.erb
<table class="tale">
  <thead>
    <tr>
      <th>会員ID</th>
      <th>氏名</th>
      <th>メールアドレス</th>
      <th>ステータス</th>
    </tr>
  </thead>
  
  <tbody>
    <%= customer.each do |customer| %>
    <tr>
      <td class="info col-xs-1">
        <%= customer.id %>
      </td>
      <td class="text-left">
        <%= link_to full_name(customer), admin_customer_path(customer) %>
      </td>
      <td class="text-left">
        <%= customer.email %>
      </td>
      <td class="col-xs-2">
        <% if customer.is_deleted == true%>
          <p class="text-secondary">退会済</p>
        <% else %>
          <p class="text-success">有効</p>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/customers/show.html.erb
<% provide(:title, "会員情報詳細") %>
<div class="container">
  <h2 class="mt-5 text-center"><%= full_name(@customer) %>さんの会員詳細</h2>
    <div class="row m-5">
      <div class="col-10 offset-1">
        <table class="table">
          <tr>
            <th class="text-center">会員ID</th>
            <td><%= @customer.id%></td>
          </tr>
          <tr>
            <th class="text-center">氏名</th>
            <td><%= full_name(@customer) %></td>
          </tr>
          <tr>
            <th class="text-center">フリガナ</th>
            <td><%= kana_full_name(@customer)%></td>
          </tr>
          <tr>
            <th class="text-center">郵便番号</th>
            <td><%= @customer.postal_code%></td>
          </tr>
          <tr>
            <th class="text-center">住所</th>
            <td><%= @customer.address%></td>
            </tr>
          <tr>
            <th class="text-center">電話番号</th>
            <td><%= @customer.phone_number%></td>
          </tr>
          <tr>
            <th class="text-center">メールアドレス</th>
            <td><%= @customer.email%></td>
          </tr>
          <tr>
            <th class="text-center">会員ステータス</th>
            <% if @customer.is_deleted == true%>
            <td class="text-secondary">退会済み</td>
            <% else %>
            <td class="text-success">有効</td>
            <% end %>
          </tr>            
        </table>
        <div class="d-flex justify-content-around">
          <p><%= link_to "編集する",edit_admin_customer_path, class:"btn btn-success"%></p>
          <p><%= link_to "注文履歴一覧を見る",admin_orders_path, class:"btn btn-primary"%></p>
        </div>
   　  </div>
  　</div>
 </div>
 