config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  scope module: :public do
    resource :customers, only: [:show, :edit, :update]
    resources :items, only: [:index]
    resources :cart_items, only: [:index]
    get '/about' => 'homes#about'
  end

  namespace :admin do
    root to:'homes#top'
    resources :items
    resources :customers, only: [:index]
    resources :genres, only: [:index]
  end
  end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      @genres = Genre.all
    else
      @genres = Genre.all
      render :index
    end
  end
  
  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      flash[:notice] = "変更内容を更新しました。"
      redirect_to admin_genres_path
    else
      flash[:alert] = "変更内容に不備があります。"
      render "edit"
    end
  end
  
  private
  
  def genre_params
    params.require(:genre).permit(:name)
  end
  
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/edit.html.erb
<% provide(:title, "ジャンル編集") %>
<div class="container mt-5 mb-5">
  <div class="row">
    <div class="col">
      <h2 class="text-center">ジャンル編集</h2>
    </div>
  </div>
    
  <div class="row justify-content-center">
    <div class="col-5">
      <%= form_with model: @genre,url: admin_genre_path, method: :patch, local: true do |f| %>
        <div class="form-group">
          <%= f.label "ジャンル名",class:"form-label" %>
          <%= f.text_field :name,class:"form-control" %>
        </div>
        <div class="col-md justify-content-around">
          <%=f.submit "変更を保存", class:"btn btn-success my-3 mr-3" %>
          <%= link_to "ジャンル一覧へ戻る",admin_genres_path, class:"btn btn-outline-secondary"%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/genres/genre_new.html.erb
<% genre.each do |genre| %>
  <tr>
    <td><%= genre.name %></td>
    <td><%= link_to "編集する", edit_admin_genre_path(genre), class:"btn btn-success py-0" %></td>
  </tr>
<% end %>

app/views/admin/genres/index.html.erb
<% provide(:title, "ジャンル一覧") %>
<div class="container">
  <div class="row text-center">
    <div class="col-md-12 mt-5">
      <h2>ジャンル一覧・追加</h2>
    </div>
  </div>
  <div class="row my-5 d-flex justify-content-center">
    <div class="col-xs-12">
      <%= form_with model: @genre,url: admin_genres_path,method: :post, remote: true do |f| %>
        <%= f.label :name, "ジャンル名" %>
        <%= f.text_field :name, id: "form" %>
        <%= f.submit "追加する", class:"btn btn-success ml-4 py-1" %>
      <% end %>
    </div>
  </div>
    
  <div class="row my-5 justify-content-center">
    <div class="col-lg-5 mt-3">
      <table class="table">
        <thead>
          <tr>
            <th>ジャンル</th>
            <th></th>
          </tr>
        </thead>
        <tbody  id="genre_index_new">
          <%= render 'genre_new', genre: @genres %>
        </tbody>
      </table>
    </div>
  </div>
</div>